from rest_framework import serializers
from apps.pages.models import SiteSettings


class SiteSettingsSerializer(serializers.ModelSerializer):
    class Meta:
        model = SiteSettings
        fields = [
            'site_name',
            'site_title',
            'site_description',
            'site_keywords',
            'logo_light',
            'logo_dark',
            'favicon',
            'primary_color',
            'secondary_color',
            'accent_color',
            'enable_splash_screen',
            'enable_custom_cursor',
            'enable_newsletter',
            'enable_chat',
            'enable_booking',
            'enable_reviews',
            'enable_wishlist',
            'min_booking_days',
            'max_booking_days',
            'advance_booking_days',
            'cancellation_hours',
            'currency',
            'tax_rate',
            'service_fee',
            'support_email',
            'support_phone',
            'whatsapp_number',
            'facebook_url',
            'instagram_url',
            'twitter_url',
            'linkedin_url',
            'youtube_url',
            'tiktok_url',
            'google_analytics_id',
            'facebook_pixel_id',
            'google_tag_manager_id',
            'maintenance_mode',
            'maintenance_message_en',
            'maintenance_message_ru',
            'maintenance_message_az',
            'maintenance_description_en',
            'maintenance_description_ru',
            'maintenance_description_az',
            'maintenance_message',
            'maintenance_end_time',
            'enable_caching',
            'cache_timeout',
            'enable_image_optimization',
            'enable_email_notifications',
            'enable_sms_notifications',
            'enable_push_notifications',
            'terms_url',
            'privacy_url',
            'cookie_policy_url',
            'enable_cookie_consent',
        ]
