# Generated by Django 5.2.8 on 2026-04-18 02:43

import apps.blog.utils.file_paths
import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import functools
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('name_az', models.CharField(help_text='Enter the unique name of the domain (max 150 characters).', max_length=150, unique=True, verbose_name='Name-(Az)')),
                ('name_ru', models.CharField(help_text='Enter the unique name of the domain (max 150 characters).', max_length=150, unique=True, verbose_name='Name-(Ru)')),
                ('name_en', models.CharField(help_text='Enter the unique name of the domain (max 150 characters).', max_length=150, unique=True, verbose_name='Name-(En)')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('title_az', models.CharField(help_text='Enter the title of the news item', max_length=255, verbose_name='Azerbaijani title')),
                ('title_ru', models.CharField(help_text='Enter the title of the news item', max_length=255, verbose_name='Russian title')),
                ('title_en', models.CharField(help_text='Enter the title of the news item', max_length=255, verbose_name='English title')),
                ('content_az', ckeditor.fields.RichTextField(blank=True, help_text='Enter the content of the news item', null=True, verbose_name='Azerbaijani content')),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, help_text='Enter the content of the news item', null=True, verbose_name='Russian content')),
                ('content_en', ckeditor.fields.RichTextField(blank=True, help_text='Enter the content of the news item', null=True, verbose_name='English content')),
                ('poster', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload an image for the news item', null=True, upload_to=functools.partial(apps.blog.utils.file_paths.upload_to_factory, *(), **{'base_path': 'news/news/%Y/%m/%d/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp', 'png'])], verbose_name='News Poster')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('message', ckeditor.fields.RichTextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Message')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsCommentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], help_text='Select a rating between 1 and 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('name_az', models.CharField(help_text='Enter the name of the tag (max 255 characters).', max_length=255, unique=True, verbose_name='Name-(Az)')),
                ('name_ru', models.CharField(help_text='Enter the name of the tag (max 255 characters).', max_length=255, unique=True, verbose_name='Name-(Ru)')),
                ('name_en', models.CharField(help_text='Enter the name of the tag (max 255 characters).', max_length=255, unique=True, verbose_name='Name-(En)')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('title_az', models.CharField(help_text='Enter the name of the category item', max_length=100, verbose_name='Title-(Az)')),
                ('title_ru', models.CharField(help_text='Enter the name of the category item', max_length=100, verbose_name='Title-(Ru)')),
                ('title_en', models.CharField(help_text='Enter the name of the category item', max_length=100, verbose_name='Title-(En)')),
                ('poster', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload an image to represent the category.', null=True, upload_to=functools.partial(apps.blog.utils.file_paths.upload_to_factory, *(), **{'base_path': 'news/news/%Y/%m/%d/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp', 'png'])], verbose_name='Category Poster')),
                ('domain', models.ForeignKey(blank=True, help_text='Select the domain this category belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='blog.domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-created_at',),
            },
        ),
    ]
