# Generated by Django 5.2.8 on 2026-04-18 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(help_text='The user who created the news item', on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(help_text='Select a category for the news item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='blog.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='news',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.news', verbose_name='News'),
        ),
        migrations.AddField(
            model_name='newscommentrating',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comment_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='newscommentrating',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blog.newscomment', verbose_name='News Comment'),
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Select a Tag for the product.', related_name='news', to='blog.tag', verbose_name='Tag'),
        ),
        migrations.AddIndex(
            model_name='newscomment',
            index=models.Index(fields=['news', '-created_at'], name='blog_newsco_news_id_ef692f_idx'),
        ),
        migrations.AddConstraint(
            model_name='newscommentrating',
            constraint=models.UniqueConstraint(fields=('comment', 'author'), name='unique_news_comment_author_rating'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category', '-created_at'], name='blog_news_categor_42945a_idx'),
        ),
    ]
