# Generated by Django 5.2.8 on 2026-05-08 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.newscomment', verbose_name='Parent Comment'),
        ),
        migrations.AddIndex(
            model_name='newscomment',
            index=models.Index(fields=['parent', '-created_at'], name='blog_newsco_parent__505146_idx'),
        ),
    ]
