# Generated by Django 5.2.8 on 2026-04-18 02:57

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('title_az', models.CharField(help_text='Enter the title of the room item', max_length=255, verbose_name='Azerbaijani title')),
                ('title_en', models.CharField(help_text='Enter the title of the room item', max_length=255, verbose_name='English title')),
                ('title_ru', models.CharField(help_text='Enter the title of the room item', max_length=255, verbose_name='Russian title')),
                ('subtitle_az', models.CharField(help_text='Enter the subtitle of the room item', max_length=255, verbose_name='Azerbaijani subtitle')),
                ('subtitle_en', models.CharField(help_text='Enter the subtitle of the room item', max_length=255, verbose_name='English subtitle')),
                ('subtitle_ru', models.CharField(help_text='Enter the subtitle of the room item', max_length=255, verbose_name='Russian subtitle')),
                ('excerpt_az', models.TextField(verbose_name='Azerbaijani excerpt')),
                ('excerpt_en', models.TextField(verbose_name='English excerpt')),
                ('excerpt_ru', models.TextField(verbose_name='Russian excerpt')),
                ('description_az', ckeditor.fields.RichTextField(verbose_name='Azerbaijani description')),
                ('description_en', ckeditor.fields.RichTextField(verbose_name='English description')),
                ('description_ru', ckeditor.fields.RichTextField(verbose_name='Russian description')),
                ('poster', models.FileField(blank=True, help_text='Upload an image', null=True, upload_to='room/%Y/%d/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp', 'png'])], verbose_name='Poster')),
                ('capacity_adult', models.PositiveSmallIntegerField(default=1, help_text='Maximum number of adults allowed (0–10).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Adults capacity')),
                ('capacity_children', models.PositiveSmallIntegerField(default=0, help_text='Maximum number of childs allowed (0–10).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Child capacity')),
                ('room_count', models.PositiveSmallIntegerField(default=1, help_text='Total number of rooms of this type available in the hotel', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Rooms')),
                ('price', models.FloatField(default=0.0, help_text='Enter a value between 0 and 10,000,000.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='Price')),
                ('discount', models.IntegerField(blank=True, default=0, help_text='Enter the discount as a percentage (0–100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount percentage')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoomIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('default', '✨'), ('faBtc', '₿'), ('aim', '🎯'), ('google', '🔎'), ('location', '📍'), ('email', '✉️'), ('phone', '📞'), ('whatsapp', '💬'), ('twitter', '🐦'), ('facebook', '📘'), ('instagram', '📸'), ('linkedin', '💼'), ('youtube', '▶️'), ('github', '🐙'), ('people', '👥'), ('sofa', '🛋️'), ('bed', '🛏️'), ('shower', '🚿'), ('wifi', '📶'), ('conditioner', '❄️'), ('light', '💡'), ('pool', '🏊\u200d♂️'), ('gym', '🏋️'), ('parking', '🅿️'), ('security', '📹'), ('swiming', '🤿')], db_index=True, max_length=50, verbose_name='Icon key')),
                ('label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Label')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='shop.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Icon',
                'verbose_name_plural': 'Room Icons',
            },
        ),
        migrations.CreateModel(
            name='RoomImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('image', models.FileField(help_text='Upload an image for the room', upload_to='room/%Y/%d/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp', 'png'])], verbose_name='Image')),
                ('room', models.ForeignKey(help_text='Select the room this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
            },
        ),
        migrations.CreateModel(
            name='RoomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('adults', models.PositiveSmallIntegerField(default=1, help_text='Enter how many guests will stay in the room', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Guests')),
                ('children', models.PositiveSmallIntegerField(default=0, help_text='Enter how many guests will stay in the room', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Guests')),
                ('check_in', models.DateField(help_text='Select the start date of stay', verbose_name='Check-in Date')),
                ('check_out', models.DateField(help_text='Select the end date of stay', verbose_name='Check-out Date')),
                ('rooms_reserved', models.PositiveSmallIntegerField(default=1, help_text='How many rooms of this type are booked', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rooms Reserved')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('abort', 'Aborted')], default='pending', max_length=20, verbose_name='Order Status')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Order',
                'verbose_name_plural': 'Room Orders',
                'ordering': ('-created_at',),
            },
        ),
    ]
