# Generated by Django 5.2.8 on 2026-04-24 23:51

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(db_index=True, default=0.0, help_text='Enter a value between 0 and 10,000,000.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='room',
            name='title_az',
            field=models.CharField(db_index=True, help_text='Enter the title of the room item', max_length=255, verbose_name='Azerbaijani title'),
        ),
        migrations.AlterField(
            model_name='room',
            name='title_en',
            field=models.CharField(db_index=True, help_text='Enter the title of the room item', max_length=255, verbose_name='English title'),
        ),
        migrations.AlterField(
            model_name='room',
            name='title_ru',
            field=models.CharField(db_index=True, help_text='Enter the title of the room item', max_length=255, verbose_name='Russian title'),
        ),
        migrations.AlterField(
            model_name='roomorder',
            name='adults',
            field=models.PositiveSmallIntegerField(default=1, help_text='Enter how many adults will stay in the room', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Adults'),
        ),
        migrations.AlterField(
            model_name='roomorder',
            name='check_in',
            field=models.DateField(db_index=True, help_text='Select the start date of stay', verbose_name='Check-in Date'),
        ),
        migrations.AlterField(
            model_name='roomorder',
            name='check_out',
            field=models.DateField(db_index=True, help_text='Select the end date of stay', verbose_name='Check-out Date'),
        ),
        migrations.AlterField(
            model_name='roomorder',
            name='children',
            field=models.PositiveSmallIntegerField(default=0, help_text='Enter how many children will stay in the room', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Children'),
        ),
        migrations.AlterField(
            model_name='roomorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('abort', 'Aborted')], db_index=True, default='pending', max_length=20, verbose_name='Order Status'),
        ),
        migrations.AddIndex(
            model_name='roomorder',
            index=models.Index(fields=['user', 'status'], name='shop_roomor_user_id_c3b00d_idx'),
        ),
        migrations.AddIndex(
            model_name='roomorder',
            index=models.Index(fields=['room', 'check_in', 'check_out'], name='shop_roomor_room_id_1831eb_idx'),
        ),
        migrations.AddIndex(
            model_name='roomorder',
            index=models.Index(fields=['status', 'check_in'], name='shop_roomor_status_56b6cd_idx'),
        ),
    ]
