# Generated by Django 5.2.8 on 2026-04-25 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart_order_orderitem_orderstatushistory_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='discount',
            field=models.IntegerField(default=0, help_text='Enter the discount as a percentage (0–100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount percentage'),
        ),
    ]
