# Generated by Django 6.0 on 2026-04-27 13:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_room_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount after discount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Final Amount'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('code', models.CharField(db_index=True, help_text='Unique coupon code (e.g., SUMMER2024)', max_length=50, unique=True, verbose_name='Coupon Code')),
                ('coupon_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Value')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount to use this coupon', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Order Amount')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage coupons)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Discount Amount')),
                ('valid_from', models.DateTimeField(help_text='Coupon valid from this date', verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(help_text='Coupon valid until this date', verbose_name='Valid To')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used (null = unlimited)', null=True, verbose_name='Usage Limit')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used', verbose_name='Usage Count')),
                ('user_usage_limit', models.PositiveIntegerField(default=1, help_text='Maximum times one user can use this coupon', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Per User Usage Limit')),
                ('description', models.TextField(blank=True, help_text='Internal description of the coupon', verbose_name='Description')),
                ('rooms', models.ManyToManyField(blank=True, help_text='Leave empty for all rooms', related_name='coupons', to='shop.room', verbose_name='Applicable Rooms')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.coupon', verbose_name='Coupon'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('other', 'Other')], max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Payment Status')),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='External payment gateway transaction ID', max_length=255, verbose_name='Transaction ID')),
                ('payment_gateway', models.CharField(blank=True, help_text='Name of payment gateway used (Stripe, PayPal, etc.)', max_length=50, verbose_name='Payment Gateway')),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date when payment was completed', null=True, verbose_name='Payment Date')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Refund Amount')),
                ('refund_date', models.DateTimeField(blank=True, null=True, verbose_name='Refund Date')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the payment', verbose_name='Notes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment data from gateway', verbose_name='Metadata')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='shop.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoomReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('title', models.CharField(help_text='Short title for the review', max_length=255, verbose_name='Review Title')),
                ('comment', models.TextField(help_text='Detailed review (minimum 20 characters)', validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Comment')),
                ('pros', models.TextField(blank=True, help_text='What did you like?', verbose_name='Pros')),
                ('cons', models.TextField(blank=True, help_text='What could be improved?', verbose_name='Cons')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='User actually booked this room', verbose_name='Verified Purchase')),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Review approved by admin', verbose_name='Approved')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Number of users who found this review helpful', verbose_name='Helpful Count')),
                ('order', models.ForeignKey(blank=True, help_text='Related booking order (if verified)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_reviews', to='shop.order', verbose_name='Order')),
                ('room', models.ForeignKey(help_text='Room being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.room', verbose_name='Room')),
                ('user', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='room_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Room Review',
                'verbose_name_plural': 'Room Reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='shop.roomreview', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'Review Helpful Vote',
                'verbose_name_plural': 'Review Helpful Votes',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='shop.room', verbose_name='Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'is_active'], name='shop_coupon_code_0a1744_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_to'], name='shop_coupon_valid_f_b078db_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='shop_paymen_order_i_d53bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='shop_paymen_user_id_fe541e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='shop_paymen_transac_303357_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='shop_paymen_payment_91de14_idx'),
        ),
        migrations.AddIndex(
            model_name='roomreview',
            index=models.Index(fields=['room', 'is_approved'], name='shop_roomre_room_id_0e105c_idx'),
        ),
        migrations.AddIndex(
            model_name='roomreview',
            index=models.Index(fields=['user', 'created_at'], name='shop_roomre_user_id_769db1_idx'),
        ),
        migrations.AddIndex(
            model_name='roomreview',
            index=models.Index(fields=['rating', 'is_approved'], name='shop_roomre_rating_f709d0_idx'),
        ),
        migrations.AddIndex(
            model_name='roomreview',
            index=models.Index(fields=['is_verified', 'is_approved'], name='shop_roomre_is_veri_76f8ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomreview',
            unique_together={('user', 'room', 'order')},
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['review', 'user'], name='shop_review_review__78224d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpful',
            unique_together={('review', 'user')},
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'created_at'], name='shop_wishli_user_id_fce2ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'room')},
        ),
    ]
