# Generated by Django 6.0 on 2026-05-01 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_discount_amount_order_final_amount_coupon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('title_az', models.CharField(help_text='Enter the title for the promotional video', max_length=255, verbose_name='Azerbaijani title')),
                ('title_en', models.CharField(help_text='Enter the title for the promotional video', max_length=255, verbose_name='English title')),
                ('title_ru', models.CharField(help_text='Enter the title for the promotional video', max_length=255, verbose_name='Russian title')),
                ('subtitle_az', models.CharField(help_text='Enter the subtitle for the promotional video', max_length=255, verbose_name='Azerbaijani subtitle')),
                ('subtitle_en', models.CharField(help_text='Enter the subtitle for the promotional video', max_length=255, verbose_name='English subtitle')),
                ('subtitle_ru', models.CharField(help_text='Enter the subtitle for the promotional video', max_length=255, verbose_name='Russian subtitle')),
                ('youtube_url', models.URLField(help_text='Enter the full YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='YouTube URL')),
                ('background_image', models.ImageField(blank=True, help_text='Upload a background image for the video section', null=True, upload_to='promotional_video/%Y/%m/%d/', verbose_name='Background Image')),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to display this promotional video', verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display (lower numbers appear first)', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Promotional Video',
                'verbose_name_plural': 'Promotional Videos',
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='discount',
            field=models.IntegerField(default=0, help_text='Enter the discount as a percentage (0–10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount percentage'),
        ),
    ]
