# Generated by Django 6.0 on 2026-05-05 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_promotionalvideo_alter_room_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomorder',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Applied coupon for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_orders', to='shop.coupon', verbose_name='Coupon'),
        ),
    ]
