# Generated by Django 6.0 on 2026-05-09 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_add_coupon_to_room_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of beds in the room', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Beds'),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.PositiveSmallIntegerField(default=30, help_text='Room size in square meters', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Room Size (m²)'),
        ),
        migrations.AddField(
            model_name='room',
            name='view_az',
            field=models.CharField(blank=True, default='', help_text='View from the room (e.g., Sea View, City View)', max_length=100, verbose_name='Azerbaijani View'),
        ),
        migrations.AddField(
            model_name='room',
            name='view_en',
            field=models.CharField(blank=True, default='', help_text='View from the room (e.g., Sea View, City View)', max_length=100, verbose_name='English View'),
        ),
        migrations.AddField(
            model_name='room',
            name='view_ru',
            field=models.CharField(blank=True, default='', help_text='View from the room (e.g., Sea View, City View)', max_length=100, verbose_name='Russian View'),
        ),
    ]
