# Generated by Django 5.2.8 on 2026-06-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_room_beds_room_size_room_view_az_room_view_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomicon',
            name='key',
            field=models.CharField(choices=[('default', '✨'), ('faBtc', '₿'), ('aim', '🎯'), ('google', '🔎'), ('location', '📍'), ('email', '✉️'), ('phone', '📞'), ('whatsapp', '💬'), ('twitter', '🐦'), ('facebook', '📘'), ('instagram', '📸'), ('linkedin', '💼'), ('youtube', '▶️'), ('github', '🐙'), ('tiktok', '🎵'), ('telegram', '✈️'), ('discord', '🎮'), ('reddit', '👽'), ('twitch', '🟣'), ('people', '👥'), ('sofa', '🛋️'), ('bed', '🛏️'), ('shower', '🚿'), ('wifi', '📶'), ('conditioner', '❄️'), ('light', '💡'), ('pool', '🏊\u200d♂️'), ('gym', '🏋️'), ('parking', '🅿️'), ('security', '📹'), ('swiming', '🤿')], db_index=True, max_length=50, verbose_name='Icon key'),
        ),
    ]
