from django.urls import path

from .views import (
    AdvantagesBarListView,
    BrandListView,
    SwapListView,
    SwapDetailView,
    HeroSliderListView,
    ServiceListView,
    DomainListView,
    CategoryListView,
    TagListView,
    FoodListView,
    PersonalListView,
    PersonalDetailView,
    SocialListView,
    ReviewListView,
    ReviewCreateView,
    ReviewUpdateView,
    ReviewDeleteView,
    TestimonialListView,
    HotelGalleryListView,
    GalleryCategoryListView,
    QuoteListView,
    ContactInquiryCreateView,
    HotelContactInfoView,
    SiteSettingsView,
    ToggleMaintenanceView,
    NewsletterSubscribeView,
    NewsletterUnsubscribeView,
    NewsletterCheckView,
    FAQListView,
)

urlpatterns = [
    path("advantages_bar/", AdvantagesBarListView.as_view()),
    path("brand/", BrandListView.as_view()),
    path("swap/", SwapListView.as_view()),
    path("swap/<slug:slug>/", SwapDetailView.as_view()),
    path("hero_slider/", HeroSliderListView.as_view()),
    path("service/", ServiceListView.as_view()),
    path("domains/", DomainListView.as_view()),
    path("categories/", CategoryListView.as_view()),
    path("tags/", TagListView.as_view()),
    path("food/", FoodListView.as_view()),
    path("social/", SocialListView.as_view()),
    path("personal/", PersonalListView.as_view()),
    path("personal/<slug:slug>/", PersonalDetailView.as_view()),
    path("review/list/", ReviewListView.as_view()),
    path("review/create/", ReviewCreateView.as_view()),
    path("review/<slug:slug>/", ReviewUpdateView.as_view()),
    path("review/<slug:slug>/delete/", ReviewDeleteView.as_view()),
    path("testimonial/", TestimonialListView.as_view()),
    path("gallery/", HotelGalleryListView.as_view()),
    path("gallery/categories/", GalleryCategoryListView.as_view()),
    path("quote/", QuoteListView.as_view()),
    path("contact/inquiry/", ContactInquiryCreateView.as_view()),
    path("contact/info/", HotelContactInfoView.as_view()),
    path("settings/", SiteSettingsView.as_view()),
    path("settings/maintenance/toggle/", ToggleMaintenanceView.as_view()),
    # Newsletter endpoints
    path("newsletter/subscribe/", NewsletterSubscribeView.as_view(), name="newsletter-subscribe"),
    path("newsletter/unsubscribe/", NewsletterUnsubscribeView.as_view(), name="newsletter-unsubscribe"),
    path("newsletter/check/", NewsletterCheckView.as_view(), name="newsletter-check"),
    path("faq/", FAQListView.as_view()),
]
