ICON_CHOICES = [
    ("default", "✨"),
    ("faBtc", "₿"),
    ("aim", "🎯"),
    ("google", "🔎"),
    ("location", "📍"),
    ("email", "✉️"),
    ("phone", "📞"),
    ("whatsapp", "💬"),

    ("twitter", "🐦"),
    ("facebook", "📘"),
    ("instagram", "📸"),
    ("linkedin", "💼"),
    ("youtube", "▶️"),
    ("github", "🐙"),
    ("tiktok", "🎵"),
    ("telegram", "✈️"),
    ("discord", "🎮"),
    ("reddit", "👽"),
    ("twitch", "🟣"),

    ("people", "👥"),
    ("sofa", "🛋️"),
    ("bed", "🛏️"),
    ("shower", "🚿"),
    ("wifi", "📶"),
    ("conditioner", "❄️"),
    ("light", "💡"),
    ("pool", "🏊‍♂️"),
    ("gym", "🏋️"),
    ("parking", "🅿️"),
    ("security", "📹"),
    ("swiming", "🤿"),
]