# Generated by Django 6.0.2 on 2026-05-12 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_of_birth_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='Street address or full address', max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='City of residence', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Country of residence', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time when the account was created', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Name of emergency contact person', max_length=100, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Phone number of emergency contact', max_length=20, null=True, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationality or citizenship', max_length=100, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, help_text='Passport or ID number for hotel bookings', max_length=50, null=True, verbose_name='Passport Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number with country code (e.g., +1234567890)', max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ZIP or postal code', max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, default='en', help_text='Preferred language code (en, az, ru)', max_length=10, null=True, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_booking_notifications',
            field=models.BooleanField(default=True, help_text='Receive notifications about bookings and reservations', verbose_name='Receive Booking Notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_newsletter',
            field=models.BooleanField(default=True, help_text='Subscribe to hotel newsletters and promotions', verbose_name='Receive Newsletter'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, help_text='State or province', max_length=100, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the profile was last updated', verbose_name='Updated At'),
        ),
    ]
