# Generated by Django 5.2.8 on 2026-04-18 02:59

import apps.pages.models.service
import apps.pages.utils.file_paths
import apps.pages.utils.validators
import ckeditor.fields
import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import functools
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagesBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('icon', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload icon.', null=True, upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'advantages_bar/%Y/%m/%d', 'force_ext': 'webp'}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Icon')),
                ('logo_svg', models.FileField(blank=True, help_text='Upload SVG logo.', null=True, upload_to='advantages_bar/svg/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg']), apps.pages.utils.validators.SVGValidator()], verbose_name='Advantages Bar Logo (SVG)')),
                ('title_en', models.CharField(help_text='Enter the Advantages Bar title in English (optional).', max_length=255, verbose_name='Title (EN)')),
                ('title_ru', models.CharField(blank=True, help_text='Enter the Advantages Bar title in Russian (optional).', max_length=255, verbose_name='Title (RU)')),
                ('title_az', models.CharField(blank=True, help_text='Enter the Advantages Bar title (main language).', max_length=255, verbose_name='Title (AZ)')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, help_text='Optional content or descriptions', verbose_name='Content (EN)')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, help_text='Optional content or descriptions', verbose_name='Content (RU)')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, help_text='Optional description for the advantages bar.', verbose_name='Description (AZ)')),
            ],
            options={
                'verbose_name': 'Advantages Bar',
                'verbose_name_plural': 'Advantages Bars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('name_en', models.CharField(help_text='Enter the brand name (max 255 characters).', max_length=255, verbose_name='Brand (EN)')),
                ('name_az', models.CharField(blank=True, help_text='Enter the brand name (max 255 characters).', max_length=255, verbose_name='Brand (AZ)')),
                ('name_ru', models.CharField(blank=True, help_text='Enter the brand name (max 255 characters).', max_length=255, verbose_name='Brand (RU)')),
                ('logo', imagekit.models.fields.ProcessedImageField(help_text='Upload an image to represent the brand.', upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'brand/logos/%Y/%m/%d/', 'force_ext': 'webp'}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Brand Logo')),
                ('logo_svg', models.FileField(blank=True, help_text='Upload SVG logo.', null=True, upload_to='brand/logos/svg/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg']), apps.pages.utils.validators.SVGValidator()], verbose_name='Brand Logo (SVG)')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('name_en', models.CharField(help_text='Enter the unique name of the domain (max 150 characters).', max_length=150, unique=True, verbose_name='Domain Name')),
                ('name_ru', models.CharField(blank=True, help_text='Enter the unique name of the domain in Russian (max 150 characters).', max_length=150, unique=True, verbose_name='Domain Name (RU)')),
                ('name_az', models.CharField(blank=True, help_text='Enter the unique name of the domain in Azerbaijani (max 150 characters).', max_length=150, unique=True, verbose_name='Domain Name (AZ)')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('title_en', models.CharField(help_text='Enter the title of the room', max_length=255, verbose_name='Title-(En)')),
                ('title_ru', models.CharField(help_text='Enter the title of the room', max_length=255, verbose_name='Title-(Ru)')),
                ('title_az', models.CharField(help_text='Enter the title of the room', max_length=255, verbose_name='Title-(Az)')),
                ('cover', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload an image', null=True, upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'rooms/rooms/%Y/%m/%d/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp', 'png'])], verbose_name='Poster')),
                ('price', models.FloatField(blank=True, default=0.0, help_text='Enter a value between 0 and 10,000,000.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('card_icon', models.FileField(help_text='Add to card only icon svg please!', upload_to='service/card/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png']), apps.pages.utils.validators.SVGValidator()], verbose_name='icon svg')),
                ('title_az', models.CharField(help_text='Title for azerbaijani language', max_length=255, verbose_name='title azerbaijani')),
                ('title_ru', models.CharField(help_text='Title for russian language', max_length=255, verbose_name='title russian')),
                ('title_en', models.CharField(help_text='Title for english language', max_length=255, verbose_name='title english')),
                ('description_en', models.TextField(blank=True, help_text='Short description for the service', null=True, verbose_name='Description-(En)')),
                ('description_ru', models.TextField(blank=True, help_text='Short description for the service', null=True, verbose_name='Description-(Ru)')),
                ('description_az', models.TextField(blank=True, help_text='Short description for the service', null=True, verbose_name='Description-(Az)')),
                ('cover_img', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload a cover image for the service', null=True, upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'services/%Y/%m/%d/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Cover image')),
                ('card_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload an image for the service card', null=True, upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'services/card_images/%Y/%m/%d/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Card image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('title_az', models.CharField(help_text='Enter the title of the social media platform', max_length=150, verbose_name='Title-(Az)')),
                ('title_ru', models.CharField(help_text='Enter the title of the social media platform', max_length=150, verbose_name='Title-(Ru)')),
                ('title_en', models.CharField(help_text='Enter the title of the social media platform', max_length=150, verbose_name='Title-(En)')),
                ('url', models.URLField(blank=True, help_text='The URL to the social network profile or page', max_length=150, unique=True, verbose_name='Social Network URL')),
                ('icon', models.CharField(blank=True, choices=[('default', '✨'), ('faBtc', '₿'), ('aim', '🎯'), ('google', '🔎'), ('location', '📍'), ('email', '✉️'), ('phone', '📞'), ('whatsapp', '💬'), ('twitter', '🐦'), ('facebook', '📘'), ('instagram', '📸'), ('linkedin', '💼'), ('youtube', '▶️'), ('github', '🐙'), ('people', '👥'), ('sofa', '🛋️'), ('bed', '🛏️'), ('shower', '🚿'), ('wifi', '📶'), ('conditioner', '❄️'), ('light', '💡'), ('pool', '🏊\u200d♂️'), ('gym', '🏋️'), ('parking', '🅿️'), ('security', '📹'), ('swiming', '🤿')], help_text='Select an icon representing the social media platform.', max_length=50, null=True, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('label', models.CharField(help_text='Short label or category for the swap event.', max_length=50, verbose_name='Label for Swap')),
                ('title_az', models.CharField(help_text='Title of the swap event.', max_length=150, verbose_name='Title-(Az)')),
                ('title_ru', models.CharField(help_text='Title of the swap event.', max_length=150, verbose_name='Title-(Ru)')),
                ('title_en', models.CharField(help_text='Title of the swap event.', max_length=150, verbose_name='Title-(En)')),
                ('content_az', ckeditor.fields.RichTextField(help_text='Optional description or additional text.', verbose_name='Content-(Az)')),
                ('content_ru', ckeditor.fields.RichTextField(help_text='Optional description or additional text.', verbose_name='Content-(Ru)')),
                ('content_en', ckeditor.fields.RichTextField(help_text='Optional description or additional text.', verbose_name='Content-(En)')),
                ('poster', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload a poster images.', null=True, upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'swaps/posters/%Y/%m/%d/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp', 'png'])], verbose_name='Poster Images')),
            ],
            options={
                'verbose_name': 'Swap',
                'verbose_name_plural': 'Swaps',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('name_az', models.CharField(help_text='Enter the name of the tag (max 255 characters).', max_length=255, verbose_name='Name-(Az)')),
                ('name_ru', models.CharField(help_text='Enter the name of the tag (max 255 characters).', max_length=255, verbose_name='Name-(Ru)')),
                ('name_en', models.CharField(help_text='Enter the name of the tag (max 255 characters).', max_length=255, verbose_name='Name-(En)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('title_en', models.CharField(help_text='Enter the name of the category item', max_length=250, verbose_name='Title of the category')),
                ('title_ru', models.CharField(blank=True, help_text='Enter the name of the category item in Russian', max_length=250, verbose_name='Title of the category (RU)')),
                ('title_az', models.CharField(blank=True, help_text='Enter the name of the category item in Azerbaijani', max_length=250, verbose_name='Title of the category (AZ)')),
                ('poster', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload an image to represent the category.', null=True, upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'categories/%Y/%m/%d/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Category Poster')),
                ('logo', imagekit.models.fields.ProcessedImageField(help_text='Upload an image to represent the brand.', upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'brand/logos/%Y/%m/%d/', 'force_ext': 'webp'}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Brand Logo')),
                ('domain', models.ForeignKey(blank=True, help_text='Select the domain this category belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pages.domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('title_en', models.CharField(help_text='Title displayed on the hero slider.', max_length=255, verbose_name='Title-(EN)')),
                ('title_ru', models.CharField(help_text='Title displayed on the hero slider.', max_length=255, verbose_name='Title-(RU)')),
                ('title_az', models.CharField(help_text='Title displayed on the hero slider.', max_length=255, verbose_name='Title-(AZ)')),
                ('subtitle_az', models.CharField(blank=True, help_text='Subtitle displayed on the hero slider.', max_length=255, null=True, verbose_name='Subtitle (AZ)')),
                ('subtitle_ru', models.CharField(blank=True, help_text='Subtitle displayed on the hero slider.', max_length=255, null=True, verbose_name='Subtitle-(RU)')),
                ('subtitle_en', models.CharField(blank=True, help_text='Subtitle displayed on the hero slider.', max_length=255, null=True, verbose_name='Subtitle-(EN)')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detailed description for the hero slider.', null=True, verbose_name='Description-(EN)')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detailed description for the hero slider.', null=True, verbose_name='Description-(RU)')),
                ('description_az', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detailed description for the hero slider.', null=True, verbose_name='Description-(AZ)')),
                ('poster', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload an image for the hero slider.', null=True, upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'hero_slider/%Y/%m/%d/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp', 'png'])], verbose_name='Slider Image')),
                ('brand', models.ForeignKey(blank=True, help_text='Brand connected with the slider.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_sliders', to='pages.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('message', ckeditor.fields.RichTextField(help_text='Enter a Message (minimum 10 characters)', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Message')),
                ('author', models.ForeignKey(help_text='The user who wrote the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoomIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('default', '✨'), ('faBtc', '₿'), ('aim', '🎯'), ('google', '🔎'), ('location', '📍'), ('email', '✉️'), ('phone', '📞'), ('whatsapp', '💬'), ('twitter', '🐦'), ('facebook', '📘'), ('instagram', '📸'), ('linkedin', '💼'), ('youtube', '▶️'), ('github', '🐙'), ('people', '👥'), ('sofa', '🛋️'), ('bed', '🛏️'), ('shower', '🚿'), ('wifi', '📶'), ('conditioner', '❄️'), ('light', '💡'), ('pool', '🏊\u200d♂️'), ('gym', '🏋️'), ('parking', '🅿️'), ('security', '📹'), ('swiming', '🤿')], max_length=50, verbose_name='Icon Type')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='pages.room', verbose_name='Room Icon')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('subtitle_az', models.CharField(blank=True, help_text='Subtitle for the feature section', max_length=255, null=True, verbose_name='Subtitle-(Az)')),
                ('subtitle_ru', models.CharField(blank=True, help_text='Subtitle for the feature section', max_length=255, null=True, verbose_name='Subtitle-(Ru)')),
                ('subtitle_en', models.CharField(blank=True, help_text='Subtitle for the feature section', max_length=255, null=True, verbose_name='Subtitle-(En)')),
                ('title_en', models.CharField(blank=True, help_text='Title for the feature section', max_length=255, null=True, verbose_name='Title-(En)')),
                ('title_ru', models.CharField(blank=True, help_text='Title for the feature section', max_length=255, null=True, verbose_name='Title-(Ru)')),
                ('title_az', models.CharField(blank=True, help_text='Title for the feature section', max_length=255, null=True, verbose_name='Title-(Az)')),
                ('content_az', ckeditor.fields.RichTextField(blank=True, help_text='Detailed content for the service feature', null=True, verbose_name='Content-(Az)')),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, help_text='Detailed content for the service feature', null=True, verbose_name='Content-(Ru)')),
                ('content_en', ckeditor.fields.RichTextField(blank=True, help_text='Detailed content for the service feature', null=True, verbose_name='Content-(En)')),
                ('service', models.OneToOneField(help_text='Feature section for the service', on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='pages.service', verbose_name='Service Feature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('icon', models.FileField(blank=True, null=True, upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'services/feature/%Y/%m/%d/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png']), apps.pages.utils.validators.SVGValidator()], verbose_name='Item Icon')),
                ('title_az', models.CharField(help_text='Service items title', max_length=255, verbose_name='Title-(Az)')),
                ('title_ru', models.CharField(help_text='Service items title', max_length=255, verbose_name='Title-(Ru)')),
                ('title_en', models.CharField(help_text='Service items title', max_length=255, verbose_name='Title-(En)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_items', to='pages.service', verbose_name='Service Feature Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='services/video_files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'mkv']), apps.pages.models.service.validate_video_size], verbose_name='Video File')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='pages.service', verbose_name='Service Video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('name_en', models.CharField(help_text='Enter the name of the person', max_length=150, verbose_name='Name-(En)')),
                ('name_ru', models.CharField(blank=True, help_text='Enter the name of the person', max_length=150, verbose_name='Name-(Ru)')),
                ('name_az', models.CharField(blank=True, help_text='Enter the name of the person', max_length=150, verbose_name='Name-(Az)')),
                ('role_en', models.CharField(help_text='Enter the role of the person', max_length=150, verbose_name='Role-(En)')),
                ('role_ru', models.CharField(blank=True, help_text='Enter the role of the person', max_length=150, verbose_name='Role-(Ru)')),
                ('role_az', models.CharField(blank=True, help_text='Enter the role of the person', max_length=150, verbose_name='Role-(Az)')),
                ('poster', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload an image for the person.', null=True, upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'personal/%Y/%m/%d/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp', 'png'])], verbose_name='Personal Image')),
                ('social', models.ManyToManyField(blank=True, help_text='Select social media profiles associated with the person.', to='pages.social', verbose_name='Social Media')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Generated automatically if left empty.', max_length=255, unique=True, verbose_name='Slug')),
                ('title_az', models.CharField(help_text='Enter the name of the food item', max_length=100, verbose_name='Title-(AZ)')),
                ('title_en', models.CharField(help_text='Enter the name of the food item', max_length=100, verbose_name='Title-(EN)')),
                ('title_ru', models.CharField(help_text='Enter the name of the food item', max_length=100, verbose_name='Title-(RU)')),
                ('subtitle_en', models.CharField(blank=True, help_text='Enter a subtitle or tagline for the food item (optional)', max_length=150, null=True, verbose_name='Subtitle-(EN)')),
                ('subtitle_ru', models.CharField(blank=True, help_text='Enter a subtitle or tagline for the food item (optional)', max_length=150, null=True, verbose_name='Subtitle-(RU)')),
                ('subtitle_az', models.CharField(blank=True, help_text='Enter a subtitle or tagline for the food item (optional)', max_length=150, null=True, verbose_name='Subtitle-(AZ)')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, help_text='Enter a detailed description of the food item', null=True, verbose_name='Description-(EN)')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, help_text='Enter a detailed description of the food item', null=True, verbose_name='Description-(RU)')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, help_text='Enter a detailed description of the food item', null=True, verbose_name='Description-(AZ)')),
                ('price', models.FloatField(default=0.0, help_text='Enter the price of the food item (must be a positive number)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Price of the food')),
                ('poster', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload an image', null=True, upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'food/%Y/%m/%d/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Poster')),
                ('tag', models.ManyToManyField(blank=True, help_text='Select tags that are relevant to this food item', related_name='foods', to='pages.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], help_text='Select a rating between 1 and 5 stars', verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the rating was created.', verbose_name='Created At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_ratings', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pages.review')),
            ],
            options={
                'db_table': 'review_ratings',
                'constraints': [models.UniqueConstraint(fields=('review', 'author'), name='unique_review_author_rating')],
            },
        ),
    ]
