# Generated by Django 5.2.8 on 2026-04-30 21:28

import apps.pages.utils.file_paths
import django.core.validators
import functools
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_gallerycategory_hotelinfo_remove_roomicon_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(help_text='Upload an image to represent the brand.', upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'brand/logos/%Y/%m/%d/', 'force_ext': 'PNG'}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Brand Logo'),
        ),
    ]
