# Generated by Django 5.2.8 on 2026-04-30 21:35

import apps.pages.utils.file_paths
import django.core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(help_text='Upload an image to represent the brand.', upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'brand/logos/%Y/%m/%d/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Brand Logo'),
        ),
    ]
