# Generated by Django 6.0 on 2026-05-01 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_brand_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('name_az', models.CharField(help_text='Enter the customer name', max_length=255, verbose_name='Azerbaijani name')),
                ('name_en', models.CharField(help_text='Enter the customer name', max_length=255, verbose_name='English name')),
                ('name_ru', models.CharField(help_text='Enter the customer name', max_length=255, verbose_name='Russian name')),
                ('role_az', models.CharField(help_text='Enter the customer role (e.g., Guest Review, Client Review)', max_length=255, verbose_name='Azerbaijani role')),
                ('role_en', models.CharField(help_text='Enter the customer role (e.g., Guest Review, Client Review)', max_length=255, verbose_name='English role')),
                ('role_ru', models.CharField(help_text='Enter the customer role (e.g., Guest Review, Client Review)', max_length=255, verbose_name='Russian role')),
                ('comment_az', models.TextField(help_text='Enter the testimonial comment', verbose_name='Azerbaijani comment')),
                ('comment_en', models.TextField(help_text='Enter the testimonial comment', verbose_name='English comment')),
                ('comment_ru', models.TextField(help_text='Enter the testimonial comment', verbose_name='Russian comment')),
                ('image', models.ImageField(help_text='Upload customer photo', upload_to='testimonials/%Y/%m/%d/', verbose_name='Customer Image')),
                ('rating', models.FloatField(default=5.0, help_text='Rating from 0 to 5', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating')),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to display this testimonial', verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display (lower numbers appear first)', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
