# Generated by Django 6.0 on 2026-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_az', models.CharField(blank=True, max_length=255, verbose_name='Name (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Name (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Name (RU)')),
                ('position', models.CharField(max_length=255, verbose_name='Position/Role')),
                ('position_az', models.CharField(blank=True, max_length=255, verbose_name='Position (AZ)')),
                ('position_en', models.CharField(blank=True, max_length=255, verbose_name='Position (EN)')),
                ('position_ru', models.CharField(blank=True, max_length=255, verbose_name='Position (RU)')),
                ('quote', models.TextField(verbose_name='Quote Text')),
                ('quote_az', models.TextField(blank=True, verbose_name='Quote (AZ)')),
                ('quote_en', models.TextField(blank=True, verbose_name='Quote (EN)')),
                ('quote_ru', models.TextField(blank=True, verbose_name='Quote (RU)')),
                ('image', models.ImageField(upload_to='quotes/', verbose_name='Photo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified/Personal')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'pages_quote',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
