# Generated by Django 6.0 on 2026-05-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='address',
            field=models.CharField(blank=True, help_text='Enter the address', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='personal',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the age', null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='personal',
            name='bio_az',
            field=models.TextField(blank=True, help_text='Enter the biography of the person', verbose_name='Biography (Az)'),
        ),
        migrations.AddField(
            model_name='personal',
            name='bio_en',
            field=models.TextField(blank=True, help_text='Enter the biography of the person', verbose_name='Biography (En)'),
        ),
        migrations.AddField(
            model_name='personal',
            name='bio_ru',
            field=models.TextField(blank=True, help_text='Enter the biography of the person', verbose_name='Biography (Ru)'),
        ),
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter the email address', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='personal',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter the phone number', max_length=50, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='personal',
            name='website',
            field=models.URLField(blank=True, help_text='Enter the website URL', verbose_name='Website'),
        ),
    ]
