# Generated by Django 6.0 on 2026-05-05 01:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_personal_address_personal_age_personal_bio_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('name_en', models.CharField(help_text='Enter the skill name in English', max_length=100, verbose_name='Skill Name (En)')),
                ('name_ru', models.CharField(blank=True, help_text='Enter the skill name in Russian', max_length=100, verbose_name='Skill Name (Ru)')),
                ('name_az', models.CharField(blank=True, help_text='Enter the skill name in Azerbaijani', max_length=100, verbose_name='Skill Name (Az)')),
                ('value', models.PositiveIntegerField(help_text='Enter the skill level as a percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Skill Level (%)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the skill in the list', verbose_name='Order')),
                ('personal', models.ForeignKey(help_text='Select the person this skill belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='pages.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ('order', 'id'),
            },
        ),
    ]
