# Generated by Django 6.0 on 2026-05-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='blood_group',
            field=models.CharField(blank=True, help_text='Enter the blood group (e.g., A+, B-, O+, AB+)', max_length=10, verbose_name='Blood Group'),
        ),
    ]
