# Generated by Django 6.0 on 2026-05-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_personal_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text="Enter skills as JSON array: [{'name_en': 'Executive Chef', 'name_ru': '...', 'name_az': '...', 'value': 90}]", verbose_name='Skills'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
