# Generated by Django 6.0 on 2026-05-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_personal_skills_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='other', help_text='Select the social media platform', max_length=50, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.URLField(help_text='Enter the full URL to the social network profile (e.g., https://youtube.com/@hoexr)', max_length=250, verbose_name='Social Network URL'),
        ),
    ]
