# Generated by Django 6.0 on 2026-05-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_social_platform_alter_social_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='social',
        ),
        migrations.AddField(
            model_name='personal',
            name='social_links',
            field=models.JSONField(blank=True, default=list, help_text="Enter social links as JSON array: [{'platform': 'youtube', 'url': 'https://youtube.com/@hoexr'}]", verbose_name='Social Links'),
        ),
    ]
