# Generated by Django 6.0 on 2026-05-05 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_personal_social_personal_social_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='social_links',
        ),
        migrations.CreateModel(
            name='PersonalSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], db_index=True, help_text='Select the social media platform', max_length=50, verbose_name='Platform')),
                ('url', models.URLField(help_text='Enter the full URL (e.g., https://youtube.com/@hoexr)', max_length=250, verbose_name='URL')),
                ('icon', models.CharField(blank=True, choices=[('default', '✨'), ('faBtc', '₿'), ('aim', '🎯'), ('google', '🔎'), ('location', '📍'), ('email', '✉️'), ('phone', '📞'), ('whatsapp', '💬'), ('twitter', '🐦'), ('facebook', '📘'), ('instagram', '📸'), ('linkedin', '💼'), ('youtube', '▶️'), ('github', '🐙'), ('people', '👥'), ('sofa', '🛋️'), ('bed', '🛏️'), ('shower', '🚿'), ('wifi', '📶'), ('conditioner', '❄️'), ('light', '💡'), ('pool', '🏊\u200d♂️'), ('gym', '🏋️'), ('parking', '🅿️'), ('security', '📹'), ('swiming', '🤿')], help_text='Optional: Select a custom icon', max_length=50, null=True, verbose_name='Icon')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='pages.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Personal Social Link',
                'verbose_name_plural': 'Personal Social Links',
                'constraints': [models.UniqueConstraint(fields=('personal', 'platform'), name='unique_personal_social')],
            },
        ),
    ]
