# Generated by Django 6.0 on 2026-05-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_personal_social_links_personalsocial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personalsocial',
            name='unique_personal_social',
        ),
        migrations.AddField(
            model_name='personal',
            name='social_links',
            field=models.JSONField(blank=True, default=list, help_text="Enter social links as JSON array: [{'platform': 'youtube', 'url': 'https://youtube.com/@hoexr'}]", verbose_name='Social Links'),
        ),
        migrations.DeleteModel(
            name='PersonalSocial',
        ),
    ]
