# Generated by Django 6.0 on 2026-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_personalsocial_unique_personal_social_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='social_links',
        ),
        migrations.AddField(
            model_name='personal',
            name='social',
            field=models.ManyToManyField(blank=True, help_text='Select social media profiles associated with the person.', to='pages.social', verbose_name='Social Media'),
        ),
    ]
