# Generated by Django 5.2.8 on 2026-05-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_remove_personal_skills_remove_social_platform_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='PersonalSkill',
        ),
        migrations.AlterModelOptions(
            name='personalskill',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Personal Skill', 'verbose_name_plural': 'Personal Skills'},
        ),
    ]
