# Generated by Django 6.0 on 2026-05-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_rename_skill_personalskill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='social',
        ),
        migrations.CreateModel(
            name='PersonalSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('url', models.URLField(help_text='Enter your personal URL for this social platform', max_length=250, verbose_name='Personal URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order', verbose_name='Order')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='pages.personal', verbose_name='Personal')),
                ('social', models.ForeignKey(help_text='Select the social media platform', on_delete=django.db.models.deletion.CASCADE, to='pages.social', verbose_name='Social Platform')),
            ],
            options={
                'verbose_name': 'Personal Social Link',
                'verbose_name_plural': 'Personal Social Links',
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('personal', 'social'), name='unique_personal_social_link')],
            },
        ),
    ]
