# Generated by Django 6.0 on 2026-05-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_social_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='social',
            field=models.ManyToManyField(blank=True, help_text='Select social media profiles associated with the person.', through='pages.PersonalSocialLink', to='pages.social', verbose_name='Social Media'),
        ),
    ]
