# Generated by Django 6.0 on 2026-05-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_add_social_with_through'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='url',
        ),
    ]
