# Generated by Django 5.2.8 on 2026-05-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_remove_url_from_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Hotel location latitude', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Hotel location longitude', max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
