# Generated by Django 5.2.8 on 2026-05-08 16:57

import apps.pages.utils.file_paths
import django.core.validators
import functools
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_hotelinfo_latitude_hotelinfo_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of the last update.', verbose_name='Last Updated')),
                ('site_name', models.CharField(default='Hoexr Luxury Hotel', help_text='Name of the website', max_length=255, verbose_name='Site Name')),
                ('site_title', models.CharField(default='Hoexr - Luxury Hotel & Resort', help_text='Browser tab title', max_length=255, verbose_name='Site Title')),
                ('site_description', models.TextField(blank=True, help_text='Short description of the site', verbose_name='Site Description')),
                ('site_keywords', models.TextField(blank=True, help_text='SEO keywords, comma separated', verbose_name='Site Keywords')),
                ('logo_light', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Logo for light backgrounds', null=True, upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'settings/logos/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='Light Logo')),
                ('logo_dark', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Logo for dark backgrounds', null=True, upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'settings/logos/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='Dark Logo')),
                ('favicon', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Site favicon (32x32 or 64x64)', null=True, upload_to=functools.partial(apps.pages.utils.file_paths.upload_to_factory, *(), **{'base_path': 'settings/favicon/', 'force_ext': None}), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'svg'])], verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#aa8453', help_text='Main brand color (hex format: #RRGGBB)', max_length=7, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#141212', help_text='Secondary brand color (hex format: #RRGGBB)', max_length=7, verbose_name='Secondary Color')),
                ('accent_color', models.CharField(default='#be9867', help_text='Accent color for highlights (hex format: #RRGGBB)', max_length=7, verbose_name='Accent Color')),
                ('enable_splash_screen', models.BooleanField(default=True, help_text='Show splash screen on site load', verbose_name='Enable Splash Screen')),
                ('enable_newsletter', models.BooleanField(default=True, help_text='Show newsletter subscription form', verbose_name='Enable Newsletter')),
                ('enable_chat', models.BooleanField(default=False, help_text='Enable live chat widget', verbose_name='Enable Live Chat')),
                ('enable_booking', models.BooleanField(default=True, help_text='Enable room booking functionality', verbose_name='Enable Booking')),
                ('enable_reviews', models.BooleanField(default=True, help_text='Allow users to leave reviews', verbose_name='Enable Reviews')),
                ('enable_wishlist', models.BooleanField(default=True, help_text='Allow users to save favorite rooms', verbose_name='Enable Wishlist')),
                ('min_booking_days', models.PositiveIntegerField(default=1, help_text='Minimum number of days for booking', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Booking Days')),
                ('max_booking_days', models.PositiveIntegerField(default=30, help_text='Maximum number of days for booking', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Booking Days')),
                ('advance_booking_days', models.PositiveIntegerField(default=365, help_text='How many days in advance can users book', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Advance Booking Days')),
                ('cancellation_hours', models.PositiveIntegerField(default=24, help_text='Hours before check-in for free cancellation', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cancellation Hours')),
                ('currency', models.CharField(default='USD', help_text='Default currency code (USD, EUR, GBP, etc.)', max_length=3, verbose_name='Currency')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tax Rate (%)')),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed service fee amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Service Fee')),
                ('support_email', models.EmailField(blank=True, help_text='Email for customer support', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Support Email')),
                ('support_phone', models.CharField(blank=True, help_text='Phone number for support', max_length=20, verbose_name='Support Phone')),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp contact number', max_length=20, verbose_name='WhatsApp Number')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok URL')),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA tracking ID (e.g., G-XXXXXXXXXX)', max_length=50, verbose_name='Google Analytics ID')),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='Facebook Pixel tracking ID', max_length=50, verbose_name='Facebook Pixel ID')),
                ('google_tag_manager_id', models.CharField(blank=True, help_text='GTM container ID (e.g., GTM-XXXXXXX)', max_length=50, verbose_name='Google Tag Manager ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode (site will be unavailable)', verbose_name='Maintenance Mode')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to display during maintenance', verbose_name='Maintenance Message')),
                ('maintenance_end_time', models.DateTimeField(blank=True, help_text='Expected end time of maintenance', null=True, verbose_name='Maintenance End Time')),
                ('enable_caching', models.BooleanField(default=True, help_text='Enable server-side caching', verbose_name='Enable Caching')),
                ('cache_timeout', models.PositiveIntegerField(default=3600, help_text='Cache timeout in seconds', verbose_name='Cache Timeout (seconds)')),
                ('enable_image_optimization', models.BooleanField(default=True, help_text='Automatically optimize uploaded images', verbose_name='Enable Image Optimization')),
                ('enable_email_notifications', models.BooleanField(default=True, help_text='Send email notifications to users', verbose_name='Enable Email Notifications')),
                ('enable_sms_notifications', models.BooleanField(default=False, help_text='Send SMS notifications to users', verbose_name='Enable SMS Notifications')),
                ('enable_push_notifications', models.BooleanField(default=False, help_text='Send push notifications to users', verbose_name='Enable Push Notifications')),
                ('terms_url', models.URLField(blank=True, help_text='Link to terms and conditions page', verbose_name='Terms & Conditions URL')),
                ('privacy_url', models.URLField(blank=True, help_text='Link to privacy policy page', verbose_name='Privacy Policy URL')),
                ('cookie_policy_url', models.URLField(blank=True, help_text='Link to cookie policy page', verbose_name='Cookie Policy URL')),
                ('enable_cookie_consent', models.BooleanField(default=True, help_text='Show cookie consent banner', verbose_name='Enable Cookie Consent')),
                ('header_scripts', models.TextField(blank=True, help_text='Custom scripts to inject in <head> (e.g., tracking codes)', verbose_name='Header Scripts')),
                ('footer_scripts', models.TextField(blank=True, help_text='Custom scripts to inject before </body>', verbose_name='Footer Scripts')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
