# Generated by Django 5.2.8 on 2026-05-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_custom_cursor',
            field=models.BooleanField(default=False, help_text='Enable custom animated cursor effect', verbose_name='Enable Custom Cursor'),
        ),
    ]
