# Generated by Django 6.0 on 2026-05-08 20:22

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_sitesettings_enable_custom_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='message_az',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Enter a Message in Azerbaijani (minimum 10 characters)', null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Message (Azerbaijani)'),
        ),
        migrations.AddField(
            model_name='review',
            name='message_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Enter a Message in English (minimum 10 characters)', null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Message (English)'),
        ),
        migrations.AddField(
            model_name='review',
            name='message_ru',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Enter a Message in Russian (minimum 10 characters)', null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Message (Russian)'),
        ),
    ]
