# Generated by Django 6.0 on 2026-05-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_review_message_az_review_message_en_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hotelfacility',
            name='pages_hotel_is_acti_556a1c_idx',
        ),
        migrations.DeleteModel(
            name='HotelFacility',
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.hotelinfo',),
        ),
    ]
