# Generated by Django 5.2.8 on 2026-06-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_remove_hotelfacility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap',
            name='label',
        ),
        migrations.AddField(
            model_name='swap',
            name='label_az',
            field=models.CharField(default=1, help_text='Short label or category for the swap event.', max_length=50, verbose_name='Label-(Az)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swap',
            name='label_en',
            field=models.CharField(default=1, help_text='Short label or category for the swap event.', max_length=50, verbose_name='Label-(En)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swap',
            name='label_ru',
            field=models.CharField(default=1, help_text='Short label or category for the swap event.', max_length=50, verbose_name='Label-(Ru)'),
            preserve_default=False,
        ),
    ]
