# Generated by Django 5.2.8 on 2026-06-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_social_icon_alter_swap_label_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.CharField(blank=True, choices=[('default', '✨'), ('faBtc', '₿'), ('aim', '🎯'), ('google', '🔎'), ('location', '📍'), ('email', '✉️'), ('phone', '📞'), ('whatsapp', '💬'), ('twitter', '🐦'), ('facebook', '📘'), ('instagram', '📸'), ('linkedin', '💼'), ('youtube', '▶️'), ('github', '🐙'), ('tiktok', '🎵'), ('telegram', '✈️'), ('discord', '🎮'), ('reddit', '👽'), ('twitch', '🟣'), ('people', '👥'), ('sofa', '🛋️'), ('bed', '🛏️'), ('shower', '🚿'), ('wifi', '📶'), ('conditioner', '❄️'), ('light', '💡'), ('pool', '🏊\u200d♂️'), ('gym', '🏋️'), ('parking', '🅿️'), ('security', '📹'), ('swiming', '🤿')], help_text='Select an icon representing the social media platform.', max_length=150, null=True, verbose_name='Icon'),
        ),
    ]
