# Generated by Django 6.0 on 2026-06-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_alter_social_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_description_az',
            field=models.TextField(blank=True, default='Veb saytımız hazırlanır. Biz həqiqətən heyrətamiz bir şey üzərində işləyirik!', help_text='Description to display during maintenance (Azerbaijani)', verbose_name='Maintenance Description (AZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_description_en',
            field=models.TextField(blank=True, default='Our website is under construction. We are working on something really amazing!', help_text='Description to display during maintenance (English)', verbose_name='Maintenance Description (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_description_ru',
            field=models.TextField(blank=True, default='Наш сайт находится в разработке. Мы работаем над чем-то действительно удивительным!', help_text='Description to display during maintenance (Russian)', verbose_name='Maintenance Description (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message_az',
            field=models.CharField(blank=True, default='Tezliklə, Bizimlə Qalın!', help_text='Title message to display during maintenance (Azerbaijani)', max_length=255, verbose_name='Maintenance Message (AZ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message_en',
            field=models.CharField(blank=True, default='Coming Soon, Stay Tuned!', help_text='Title message to display during maintenance (English)', max_length=255, verbose_name='Maintenance Message (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message_ru',
            field=models.CharField(blank=True, default='Скоро, Оставайтесь с нами!', help_text='Title message to display during maintenance (Russian)', max_length=255, verbose_name='Maintenance Message (RU)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(blank=True, help_text='Legacy message field (use language-specific fields instead)', verbose_name='Maintenance Message (Legacy)'),
        ),
    ]
